package dev.fulfillmenthub.runtime.audit;
import static org.junit.jupiter.api.Assertions.*;
import dev.fulfillmenthub.runtime.RuntimeConfiguration;
import dev.fulfillmenthub.runtime.orders.*;
import dev.fulfillmenthub.runtime.payment.*;
import dev.fulfillmenthub.runtime.delivery.*;
import dev.fulfillmenthub.runtime.providers.ProviderResilience;
import dev.fulfillmenthub.runtime.idempotency.IdempotencyService;
import dev.fulfillmenthub.runtime.webhook.*;
import dev.fulfillmenthub.domain.*;
import jakarta.persistence.EntityManager;
import java.time.*;import java.util.*;import java.util.concurrent.*;import java.util.concurrent.atomic.*;import java.net.*;import java.nio.charset.StandardCharsets;
import com.sun.net.httpserver.*;
import org.flywaydb.core.Flyway;
import org.junit.jupiter.api.*;
import org.springframework.boot.*;
import org.springframework.boot.builder.SpringApplicationBuilder;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.boot.persistence.autoconfigure.EntityScan;
import org.springframework.context.*;
import org.springframework.context.annotation.Import;
import org.springframework.transaction.support.TransactionTemplate;
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
class AdversarialAuditIT {
 @SpringBootConfiguration @EnableAutoConfiguration @EntityScan("dev.fulfillmenthub.runtime")
 @Import({RuntimeConfiguration.class,OrderPlacementService.class,OrderService.class,IdempotencyService.class,WebhookInboxService.class,WebhookProcessingService.class})
 static class App {}
 ConfigurableApplicationContext context;EntityManager em;TransactionTemplate tx;OrderPlacementService placement;OrderService queries;WebhookInboxService inbox;WebhookProcessingService webhook;
 @BeforeAll void start(){String url=System.getProperty("it.database.url","jdbc:postgresql://127.0.0.1:55432/fulfillment"),user=System.getProperty("it.database.user","fulfillment"),password=System.getProperty("it.database.password","local-development-only");
  Flyway.configure().dataSource(url,user,password).locations("classpath:db/migration").load().migrate();
  context=new SpringApplicationBuilder(App.class).web(WebApplicationType.NONE).properties("spring.datasource.url="+url,"spring.datasource.username="+user,"spring.datasource.password="+password,"spring.flyway.enabled=false","spring.jpa.hibernate.ddl-auto=validate").run();
  em=context.getBean(EntityManager.class);tx=context.getBean(TransactionTemplate.class);placement=context.getBean(OrderPlacementService.class);queries=context.getBean(OrderService.class);inbox=context.getBean(WebhookInboxService.class);webhook=context.getBean(WebhookProcessingService.class);}
 @AfterAll void close(){if(context!=null)context.close();}
 @BeforeEach void reset(){sql("truncate webhook_events,delivery_events,deliveries,delivery_quotes,processed_messages,idempotency_records,outbox_messages,payment_attempts,payments,order_status_changes,order_items,orders,products cascade");}
 void sql(String q){tx.executeWithoutResult(s->em.createNativeQuery(q).executeUpdate());}
 String text(String q){return tx.execute(s->String.valueOf(em.createNativeQuery(q).getSingleResult()));}
 int count(String q){return tx.execute(s->((Number)em.createNativeQuery(q).getSingleResult()).intValue());}
 UUID customer;UUID product;
 UUID order(boolean paid){customer=UUID.randomUUID();product=UUID.randomUUID();tx.executeWithoutResult(s->em.persist(ProductRow.create(product,"SKU-"+product.toString().substring(0,8),"item",new java.math.BigDecimal("10"),1,Instant.now())));
  UUID id=placement.place(customer,new Address("street","1",null,"district","city","SP","01001000","BR",null,null),List.of(new OrderPlacementService.Line(product,1)),Money.brl("15"),UUID.randomUUID().toString()).id();if(paid)sql("update orders set status='Paid' where id='"+id+"'");return id;}
 interface Response {void handle(HttpExchange e)throws Exception;}
 HttpServer server(Response response)throws Exception{var server=HttpServer.create(new InetSocketAddress("127.0.0.1",0),0);server.setExecutor(Executors.newVirtualThreadPerTaskExecutor());server.createContext("/",e->{try{e.getRequestBody().readAllBytes();response.handle(e);}catch(Exception ex){ex.printStackTrace();e.close();}});server.start();return server;}
 void respond(HttpExchange e,int status,String body)throws Exception{var b=body.getBytes(StandardCharsets.UTF_8);e.getResponseHeaders().set("Content-Type","application/json");e.sendResponseHeaders(status,b.length);e.getResponseBody().write(b);e.close();}
 String remote(String status){return "{\"id\":\"remote-delivery\",\"status\":\""+status+"\",\"fee\":{\"amount\":15.00,\"currency\":\"BRL\"},\"tracking_url\":\"https://example.invalid/tracking\",\"updated_at\":\""+Instant.now()+"\"}";}
 boolean common(HttpExchange e)throws Exception{if(e.getRequestURI().getPath().endsWith("/oauth/token")){respond(e,200,"{\"access_token\":\"sim_audit\",\"token_type\":\"Bearer\",\"expires_in\":300,\"scope\":\"deliveries\"}");return true;}
  if(e.getRequestURI().getPath().endsWith("/delivery_quotes")){respond(e,200,"{\"id\":\"quote-audit\",\"fee\":{\"amount\":15.00,\"currency\":\"BRL\"},\"expires_at\":\""+Instant.now().plusSeconds(300)+"\",\"estimated_dropoff_at\":\""+Instant.now().plusSeconds(1800)+"\",\"duration_minutes\":30,\"pickup_duration_minutes\":10}");return true;}return false;}
 DeliveryWorkflowService delivery(HttpServer s){return new DeliveryWorkflowService(em,tx,Clock.systemUTC(),new DeliveryProviderSettings(true,URI.create("http://127.0.0.1:"+s.getAddress().getPort()),"customer","client","secret"),new ProviderResilience());}
 @Test void permanentDeliveryRejectionMustReleaseStock()throws Exception{var id=order(true);var s=server(e->{if(!common(e))respond(e,422,"{}");});try{delivery(s).request(id);assertEquals("Cancelled",text("select status from orders where id='"+id+"'"));assertEquals(1,count("select stock_quantity from products where id='"+product+"'"),"permanent rejection must release reservation");}finally{s.stop(0);}}
 @Test void cancellationDuringRemoteCreateMustRemainCancelled()throws Exception{var id=order(true);var s=server(e->{if(!common(e)){queries.cancel(id,customer,UUID.randomUUID(),false,null);respond(e,201,remote("pending"));}});try{delivery(s).request(id);assertEquals(1,count("select stock_quantity from products where id='"+product+"'"));assertEquals("Cancelled",text("select status from orders where id='"+id+"'"),"provider completion must not resurrect cancelled order");}finally{s.stop(0);}}
 @Test void deliveredSnapshotMustNotResurrectCancelledOrder()throws Exception{var id=order(true);var state=new AtomicReference<>("pending");var s=server(e->{if(!common(e))respond(e,200,remote(state.get()));});try{var d=delivery(s);d.request(id);queries.cancel(id,customer,UUID.randomUUID(),false,null);state.set("delivered");d.verifyAndApply("remote-delivery");assertEquals("Cancelled",text("select status from orders where id='"+id+"'"));}finally{s.stop(0);}}
 @Test void returnedDeliveryMustScheduleCompensation()throws Exception{var id=order(true);var state=new AtomicReference<>("pending");var s=server(e->{if(!common(e))respond(e,200,remote(state.get()));});try{var d=delivery(s);d.request(id);state.set("returned");d.verifyAndApply("remote-delivery");assertEquals("Cancelled",text("select status from orders where id='"+id+"'"));assertEquals(1,count("select stock_quantity from products where id='"+product+"'"));assertEquals(1,count("select count(*) from outbox_messages where type='OrderCancelled'"));}finally{s.stop(0);}}
 @Test void permanentQuoteRejectionMustNotLeavePaidOrderRetrying()throws Exception{var id=order(true);var s=server(e->{if(e.getRequestURI().getPath().endsWith("/delivery_quotes"))respond(e,422,"{}");else common(e);});try{try{delivery(s).request(id);}catch(org.springframework.web.client.RestClientResponseException expected){}assertEquals("Cancelled",text("select status from orders where id='"+id+"'"));}finally{s.stop(0);}}
 @Test void ignoredWebhookRedeliveryMustBeAcknowledged()throws Exception{byte[] body="{\"id\":\"audit-ignored\",\"type\":\"informational\"}".getBytes(StandardCharsets.UTF_8);var r=inbox.store("unknown",inbox.identify(body),body,"audit");assertTrue(webhook.processOne(r.id()));assertTrue(webhook.processOne(r.id()),"Ignored is terminal and must remain ackable");}
 @Test void crashedFifthWebhookAttemptMustRecover()throws Exception{byte[] body="{\"id\":\"audit-fifth\",\"type\":\"informational\"}".getBytes(StandardCharsets.UTF_8);var r=inbox.store("unknown",inbox.identify(body),body,"audit");sql("update webhook_events set status='Processing',attempts=5,owner='"+UUID.randomUUID()+"',locked_until=now()-interval '1 second' where id='"+r.id()+"'");assertTrue(webhook.processOne(r.id()),"crashed final attempt must be recoverable or explicitly parked");}
 @Test void latePermanentPaymentResponseMustNotOverwritePaid()throws Exception{var id=order(false);sql("insert into payments(id,order_id,status,provider,provider_idempotency_key,amount_amount,amount_currency,created_at,updated_at) values ('"+UUID.randomUUID()+"','"+id+"','Pending','simulator','key-audit',25,'BRL',now(),now())");UUID payment=UUID.fromString(text("select id from payments"));var entered=new CountDownLatch(2);var settled=new CountDownLatch(1);var calls=new AtomicInteger();var s=server(e->{int n=calls.incrementAndGet();entered.countDown();if(!entered.await(10,TimeUnit.SECONDS))throw new IllegalStateException("barrier");if(n==1)respond(e,200,"{\"id\":\"pay-audit\",\"status\":\"paid\",\"amount\":{\"amount\":25,\"currency\":\"BRL\"},\"updated_at\":\""+Instant.now()+"\"}");else{if(!settled.await(10,TimeUnit.SECONDS))throw new IllegalStateException("settle barrier");respond(e,409,"{}");}});
  try{var g=new PaymentGatewayClient(em,tx,Clock.systemUTC(),new PaymentProviderSettings(true,URI.create("http://127.0.0.1:"+s.getAddress().getPort()),"audit-token"),new ProviderResilience());try(var executor=Executors.newVirtualThreadPerTaskExecutor()){var a=executor.submit(()->{g.submit(payment);settled.countDown();});var b=executor.submit(()->{g.submit(payment);settled.countDown();});a.get(20,TimeUnit.SECONDS);b.get(20,TimeUnit.SECONDS);}assertEquals("Paid",text("select status from payments"),"late 409 must not replace settled status");}finally{s.stop(0);}}
 @Test void wrongCustomerCancellationHasNoEffects(){var id=order(false);assertNull(queries.cancel(id,UUID.randomUUID(),UUID.randomUUID(),false,null));assertEquals("Created",text("select status from orders where id='"+id+"'"));assertEquals(0,count("select stock_quantity from products"));assertEquals(0,count("select count(*) from outbox_messages where type='OrderCancelled'"));}
 @Test void concurrentLastStockCannotOversell()throws Exception{var id=order(false);sql("delete from outbox_messages;delete from order_status_changes;delete from order_items;delete from orders;update products set stock_quantity=1");var start=new CountDownLatch(1);AtomicInteger success=new AtomicInteger();try(var ex=Executors.newVirtualThreadPerTaskExecutor()){List<Future<?>> fs=new ArrayList<>();for(int i=0;i<10;i++)fs.add(ex.submit(()->{try{start.await();placement.place(customer,new Address("s","1",null,"d","c","SP","01001000","BR",null,null),List.of(new OrderPlacementService.Line(product,1)),Money.brl("0"),UUID.randomUUID().toString());success.incrementAndGet();}catch(RuntimeException expected){}catch(InterruptedException e){Thread.currentThread().interrupt();}}));start.countDown();for(var f:fs)f.get(20,TimeUnit.SECONDS);}assertEquals(1,success.get());assertEquals(0,count("select stock_quantity from products"));assertEquals(1,count("select count(*) from orders"));}
 @Test void repeatedProviderSnapshotCreatesOneEvent()throws Exception{var id=order(true);var timestamp=Instant.now();var s=server(e->{if(!common(e))respond(e,200,"{\"id\":\"remote-delivery\",\"status\":\"pending\",\"fee\":{\"amount\":15,\"currency\":\"BRL\"},\"tracking_url\":\"https://example.invalid/t\",\"updated_at\":\""+timestamp+"\"}");});try{var d=delivery(s);d.request(id);d.verifyAndApply("remote-delivery");d.verifyAndApply("remote-delivery");assertEquals(1,count("select count(*) from delivery_events"));}finally{s.stop(0);}}
 @Test void missingRequiredOutboxHandlerIsNotAcknowledged(){var event=dev.fulfillmenthub.runtime.outbox.OutboxRow.pending("OrderPaid",UUID.randomUUID(),Instant.now());tx.executeWithoutResult(t->em.persist(event));var processor=new dev.fulfillmenthub.runtime.outbox.OutboxProcessor(em,tx,Clock.systemUTC(),List.of());processor.drain(1);assertEquals("Pending",text("select status from outbox_messages"));assertEquals(1,count("select attempts from outbox_messages"));}
 @Test void committedIdempotencyAssociationSurvivesIncompleteResponse(){var id=order(false);sql("delete from outbox_messages;delete from order_status_changes;delete from order_items;delete from orders;update products set stock_quantity=1");var service=context.getBean(IdempotencyService.class);String scope=UUID.randomUUID().toString();assertEquals(IdempotencyService.State.Started,service.begin(scope,"audit-crash","HASH").state());var placed=placement.place(customer,new Address("s","1",null,"d","c","SP","01001000","BR",null,null),List.of(new OrderPlacementService.Line(product,1)),Money.brl("0"),"audit-crash",scope,"audit-crash");service.release(scope,"audit-crash");var recovered=service.begin(scope,"audit-crash","HASH");assertEquals(IdempotencyService.State.Recovered,recovered.state());assertEquals(placed.id(),recovered.orderId());assertEquals(1,count("select count(*) from orders"));assertEquals(0,count("select stock_quantity from products"));}

 @Test void rawBodySignatureMustRejectTampering()throws Exception{String key="audit-webhook-key",timestamp=Long.toString(Instant.now().getEpochSecond());byte[] body="{}".getBytes(StandardCharsets.UTF_8);var mac=javax.crypto.Mac.getInstance("HmacSHA256");mac.init(new javax.crypto.spec.SecretKeySpec(key.getBytes(StandardCharsets.UTF_8),"HmacSHA256"));mac.update(timestamp.getBytes(StandardCharsets.US_ASCII));mac.update((byte)'.');String signature=java.util.HexFormat.of().formatHex(mac.doFinal(body));assertEquals(WebhookInboxService.Verification.Valid,inbox.verify(key,body,signature,timestamp,300));assertEquals(WebhookInboxService.Verification.InvalidSignature,inbox.verify(key,"{\"tampered\":true}".getBytes(StandardCharsets.UTF_8),signature,timestamp,300));}

}
